### ISSUE TITLE
Add ability to wrap existing nodes in a dom

### ISSUE THREAD

**Issue by paquettg** [paquettg/php-html-parser#14]
Add ability to wrap existing nodes in a dom

**Comment by dtchang0322** [comment]
Nice job. You may consider:
1) Add options for strip out <script> tags and <style> tags or not, since sometime they are useful.
2) DOM::outHTML is undefined for v1.6.5. It will be nice to have function DOM::save
3) source code for stringEncode is not included in src tree.
4) Give another way to activate objects without using Composer. I put stringEncode files in src directory and make codes as following to autoload objects:

spl_autoload_register(function($class) {
    $prefix1 = 'PHPHtmlParser\\';
	$prefix2 = 'stringEncode\\';
	if(strpos($class,$prefix1) !== 0 and strpos($class,$prefix2) !== 0) return;
    $location =  __DIR__ . '/../php-html-parser/src/' . str_replace('\\', '/', $class) . '.php';

    if (is_file($location)) {
        require_once($location);
    }
});

**Comment by dtchang0322** [comment]
Add ability to strip out <script> tags and <style> tags or not.
