### ISSUE TITLE
 extract innerHtml will  Remove content in {}

### ISSUE THREAD

**Issue by naughtymonkey1010** [paquettg/php-html-parser#184]
$q->load('<p>aa={123} </p>')->innerHtml  will get    aa=

**Comment by paquettg** [comment]
Hey @naughtymonkey1010,

This happens becacuse of the clean up portion removing smarty scripts, https://www.smarty.net/.

For now, you can turn off cleaning by setting the 'cleanupInput' option to false, which should resolve you current issue.

In 2.1.0 I will add the option to disable only the clean up of smarty scripts so that you don't have to turn it all off.

**Comment by paquettg** [comment]
The option to change this behavior has been added to 2.1.0.

Please let me know if you need anything further.
