### ISSUE TITLE
Issue with UTF-8

### ISSUE THREAD

**Issue by wrey75** [paquettg/php-html-parser#19]
There is something wrong due to conversion made to the text. B

```
   $dom = new Dom;
   $dom->loadFromUrl($page_url, [ 'enforceEncoding'=> 'UTF-8']);
```
The text is sometimes decoded as it should be and sometimes I have a decoding that kills my UTF-8 characters (the source is UTF-8 and I don't do any change on results grabbed `from ->text(TRUE)`function).

Not sure about a bug because I traced your code and it should not apply conversion due to the forced UTF8.

**Comment by tegansnyder** [comment]
There are a few places that could use some mb functions. I also had some issues.

For instance in https://github.com/paquettg/php-html-parser/blob/58ae44c3c7ff2f0ab6138d66c2795f8cff58985e/src/PHPHtmlParser/Dom/TextNode.php#L35

It should probably use:
```php
$text = mb_ereg_replace('\s+', ' ', $text);
```
instead of:
```php
$text = preg_replace('/\s+/', ' ', $text);
```

Also if you want to be in complete control over the encoding yourself you could completely remove the encoding functions in this library. Example: https://github.com/paquettg/php-html-parser/commit/282e4e43646e64e6d5dccf75dc44218a04bfe62d
