### ISSUE TITLE
[Proposal] Option to disable cleanup

### ISSUE THREAD

**Issue by LukasRos** [paquettg/php-html-parser#36]
There are some cases in which it might be useful to use the DOM parser to check the presence of certain <style> or <script> tags. In those cases it should be possible to pass an option to skip some of the cleaning steps that remove those tags. This option could be either as broad as "skipHtmlCleanup" or specific such as "keepScriptsInDom" or "keepStylesInDom".

**Comment by paquettg** [comment]
I like this.

**Comment by LukasRos** [comment]
Great, will you implement this or can I help you with it?

**Comment by paquettg** [comment]
I intend to add an option for each part of the clean up and one global option for all clean up.
I am more than willing to accept any help you wish to offer. The options should work similarly to the way the current options work, you pass them in trough an array of sorts. 
Keep in mind, though, that not cleaning up the tags might cause the parser to fail and that is something that would need to be looked int oand tested to ensure that nothing breaks because of a change like this.
