### ISSUE TITLE
Update to 1.6.9 breaks HTML entities

### ISSUE THREAD

**Issue by clarinetlord** [paquettg/php-html-parser#62]
When I updated to 1.6.9, it appears the way HTML entities are treated in parsed documents has changed, and it incorrectly handles some characters. The only entity I see so far that converts incorrectly is `&#x69;` (lower case "i"). When requesting a node's text with this entity in it, it returns "\n5;" instead (newline, "5", semi-colon). As soon as I reverted back to 1.6.8, it fixed it. 

Is it possible to disable all entity handling entirely, since I can easily do that myself with html_entity_decode() if I need to?

**Comment by paquettg** [comment]
Interesting, we do not do any handling of entities in the module. We do use the &#10 entity to preserve new lines though, which might be what is causing this issue for you.

I am not able to duplicate this solely with the line you provided, it just returns the correct line. I have added a test to confirm this (I'll tag this comment in my new text). 

Could you please change the test so that it breaks for you/causes the issue you are experiencing? After that is done I can get to fixing the issue.

thanks.

**Comment by paquettg** [comment]
Here is the commit that added the test.
01a9e2f28d3b82c7124a023df9ac69da704aa58c

**Comment by clarinetlord** [comment]
Thanks, I'll take a look at the test and see if I can replicate it. The newline entity you mentioned may indeed have something to do with it. It is possible that hexadecimal entities are converted to decimal ones somewhere in the process? The hex entity `&#x69;` becomes the dec entity `&#105;`, which matches my output if that entity somehow gets broken up into two parts.

**Comment by paquettg** [comment]
hey @clarinetlord,

I added a semi-color to the end of my conversion code, which really should have been their in the first place... this is probably why they have that.

This should solve the issue. Let me know if you have any other issue.

**Comment by clarinetlord** [comment]
Yep, looks like that did it! You could now change that new TextNode test if you want, to test something like `&#105;` instead of `&#x69;`, since any decimal entities starting with &#10 are what actually broke, not that particular hex entity I originally thought.
